version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: monthly
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: daily
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: daily